require('core/options')
require('core/keymaps')

require('plugins/plugins')
require('plugins/telescope')
require('plugins/lsp')
require('plugins/flutter_tools')
require('plugins/cmp')
require('plugins/lualine')
require('plugins/nvimtree')
require('plugins/tmux')
require('plugins/treesitter')
require('plugins/autopairs')
require('plugins/null-ls')
require('plugins/toggleterm')
require('plugins/cmake')
require('plugins/indent-line')
